[[main]]
  identifier = "home"
  name = "Início"
  url = "/"
  weight = 1

[[main]]
  identifier = "about"
  name = "Sobre"
  url = "/sobre/"
  weight = 4

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/registro/"
  weight = 5
    
#[[main]]
#  identifier = "anotacoes"
#  name = "Anotações"
#  url = "/anotacoes/"
#  weight = 2

  
#[[main]]
#  identifier = "graph"
#  name = "Grafos"
#  url = "/grafos/"
#  weight = 3

