baseURL = 'https://nataliapleone.github.io'
DefaultContentLanguage = "pt-br"
title = 'Natália'
theme = "hugo-theme-tokiwa"


[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/exampleFont" 
description = """ """ 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTeX$
useChineseFonts = true 
postDateFormat = "02/01/2006"


[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2





[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3



[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params.social]
github = "https://github.com/"

[outputs]
home = ["HTML", "JSON"]


